name: SignRegionWorldguard
main: kana.SignRegionWorldguard.SignRegionWorldguard
author: kana34
website: http://www.2k16.ovh
description: Permet d acheter des terrains worldguard
version: 1.2
depends: [Vault, WorldGuard, WorldEdit]
commands:
    srw:
        description: /srw reload.